### ISSUE TITLE
Complex Float32 data are not well handle

### ISSUE THREAD

**Issue by aTrotier** [MagneticResonanceImaging/MRIReco.jl#103]
While working on a benchmark against bart (which is using Float32). I wanted to create a data acq with that possibility.
One of the issue was in CartesianTrajectory3D

I had to change the type of the keyword parameters to Float32
```julia
T=Float32
 tr = MRIBase.CartesianTrajectory3D(Float32,128,128,numSlices=128,TE=T(0),AQ=T(0))
```

Should we change that ?

It is also the same issue for the reconstruction regularization parameters

**Comment by aTrotier** [comment]
I'll put that on my to do. Especially for all the high level functions.

Le ven. 9 sept. 2022 à 21:27, Tobias Knopp ***@***.***> a
écrit :

**Comment by migrosser** [comment]
Commit d1efe5d should fix the issue with the type of TE and AQ in the trajectories. Furthermore, I changed `setupIterativeReco` so that the type of lambda is adapted to the underlying datatype in AcquisitionData in commit b84a9ee

**Comment by aTrotier** [comment]
Thanks !

Le ven. 30 sept. 2022 à 19:29, migrosser ***@***.***> a
écrit :
