### ISSUE TITLE
Extremely slow multiCoil reconstruction for 32 coils

### ISSUE THREAD

**Issue by alexjaffray** [MagneticResonanceImaging/MRIReco.jl#108]
I've noticed that 32 channel reconstructions are extremely slow, even for simple Cartesian trajectories. This is new behaviour, as in release 0.5.0 I was able to perform the same reconstructions extremely quickly. 

I have added a test in the `testCartesianCG` branch which replicates this problem.

**Comment by alexjaffray** [comment]
After some playing around with things, it seems that it is related to type inference, seems like the recent changes to MRIReco and RegularizedLeastSquares result in a lot of type inference overhead.

**Comment by tknopp** [comment]
Our first reconstructions are indeed quite slow. I am not sure if our recent changes have made things worse.

**Comment by alexjaffray** [comment]
@tknopp I understand the slowness of the first reconstruction as a general Julia characteristic, however 32 coil reconstruction of a single 64 x 64 slice using simulated data with a Cartesian trajectory should not take > 2 hours on CI... See the CI runs in the testCartesianCG branch for reference. This is a significant problem which should be looked into and was not picked up on the tests since the tests only include a maximum of 8 coils in the reconstruction tasks. 

Prior to the changes (i.e in May of this year on v0.5.0) the first reconstruction time for 128 x 128 x 9 slices cartesian data with 32 coils was on the order of 30 seconds, and subsequent reconstructions took ~ 1 second. This exact same task now takes at least 2 hours, perhaps more.

**Comment by tknopp** [comment]
This should be fixed by https://github.com/MagneticResonanceImaging/MRIReco.jl/commit/b6c4c8ccc3b7a874574bfb0eda47c60300e287f3

**Comment by tknopp** [comment]
And https://github.com/MagneticResonanceImaging/MRIReco.jl/commit/d9d22032e0260d175825c3fe2bccbf4fe7d8f015 brings the TTFIR (time to first image reconstruction) from 20 s to about 3.6 s. But watch out, the first `using` will be much longer, because it does image reconstruction during precompilation. Regular using goes from 15.5 s to 19 s here. This is because it needs to load more precompiled code. But still a clear net win.

**Comment by alexjaffray** [comment]
This is great! Thanks @tknopp for doing this so quickly!

Our 32 coil reconstructions work on `master` for spiral and cartesian trajectories so I'll close the issue.

**Comment by tknopp** [comment]
Perfect, and thanks for bringing this up Alex. Otherwise we would not have been able to fix it.
