### ISSUE TITLE
example file doesn't work in Julia 1.7.3

### ISSUE THREAD

**Issue by MattEttus** [MagneticResonanceImaging/MRIReco.jl#128]
If you follow the directions in the example file, you get an error that ISMRMRDFile is not defined

julia> using MRIReco

julia> include("example.jl")
ERROR: LoadError: UndefVarError: ISMRMRDFile not defined
Stacktrace:
 [1] top-level scope
   @ ~/mri/MRIReco.jl/examples/mridataorg/example.jl:18
 [2] include(fname::String)
   @ Base.MainInclude ./client.jl:451
 [3] top-level scope
   @ REPL[2]:1
in expression starting at /home/matt/mri/MRIReco.jl/examples/mridataorg/example.jl:18

**Comment by aTrotier** [comment]
The interface to mrirecon has been changed a lot.
We should update the example. And maybe put it in the doc With literate to
see if it works

Le mer. 26 oct. 2022 à 05:20, Matt Ettus ***@***.***> a
écrit :

**Comment by aTrotier** [comment]
I have started to work on the correction : https://github.com/MagneticResonanceImaging/MRIReco.jl/pull/129

@tknopp convert3dTo2d required to have access to FFTOp. Should we move that function in MRIReco to have access to it ?

By the way maybe we should put that example in the doc with literate (if it is possible to do so)

**Comment by tknopp** [comment]
This is fixed on master and within the `0.7.1` release. We still need to fix the documentation after the package split but I will close this specific issue now.

**Comment by MattEttus** [comment]
Now fails with a different error, with bad arguments to CartesianTrajectory:

Precompiling project...
  1 dependency successfully precompiled in 4 seconds (369 already precompiled)
[ Info: download ./data/ksp_knee_3dfse.h5...
ERROR: LoadError: MethodError: no method matching CartesianTrajectory(::Int64, ::Int64; TE=0.0f0, AQ=0.001f0)
Closest candidates are:
  CartesianTrajectory(::Type{T}, ::Any, ::Any; TE, AQ, kmin, kmax, kargs...) where T at ~/.julia/packages/MRIBase/6ZkxN/src/Trajectories/2D/Cartesian2D.jl:22
Stacktrace:
 [1] convert3dTo2d(acqData::AcquisitionData{Float32, 3})
   @ MRIBase ~/.julia/packages/MRIBase/6ZkxN/src/Datatypes/AcqData.jl:379
 [2] top-level scope
   @ ~/.julia/packages/MRIReco/QqOJG/examples/mridataorg/example.jl:26
 [3] include(fname::String)
   @ Base.MainInclude ./client.jl:451
 [4] top-level scope
   @ REPL[3]:1
in expression starting at /home/matt/.julia/packages/MRIReco/QqOJG/examples/mridataorg/example.jl:26

**Comment by tknopp** [comment]
yes, a release of MRIBase was missing. Just triggers this. You will need to update once the release is tagged.
