### ISSUE TITLE
MRIHub : MRIReco.jl

### ISSUE THREAD

**Issue by aTrotier** [MagneticResonanceImaging/MRIReco.jl#159]
MRIHub has a script to automatically update the number of citation but it does not work for MRIReco.jl

I think the doi is missing in the file and the script is based on that (see : https://github.com/ISMRM/mrhub/blob/master/_data/projects.json). I suppose that the package was added to MRHub before the paper was published.

**Comment by tknopp** [comment]
Yes it was. Would be great to update that. Feel free free to make a pull request.

**Comment by aTrotier** [comment]
PR  : https://github.com/ISMRM/mrhub/pull/89
