### ISSUE TITLE
Multi-threading reconstruction along the contrast dimension

### ISSUE THREAD

**Issue by aTrotier** [MagneticResonanceImaging/MRIReco.jl#160]
In IterativeReconstruction.jl, `reconstruction_multiCoil` use @floops only along the slice and NR dimension https://github.com/MagneticResonanceImaging/MRIReco.jl/blob/5a8e4e14ceb21b7a42591bfd646a304208476396/src/Reconstruction/IterativeReconstruction.jl#L193

Do you see a reason to not also do this along the contrast dimension ?

**Comment by tknopp** [comment]
No reason. Makes sense to run that in parallel too.

**Comment by aTrotier** [comment]
#209
