### ISSUE TITLE
BrukerSequence : Problem on 2D sequence with RawAcquisitionDataFid_360

### ISSUE THREAD

**Issue by NSimonneau** [MagneticResonanceImaging/MRIReco.jl#180]
Hi,

There is error message when you try to apply the RawAcquisitionDataFid_360 on 2D bruker sequence (1 slice MGE sequence in my case). The problem come from the "acqFov" fonction who search for ["ACQ_slice_sepm"] (size of the slice separation) for the third dimension and it seems to doesn't exist anymore on Paravision 360. 

Thanks

**Comment by aTrotier** [comment]
It seems this parameter is missing in the Bruker MGE sequence. Maybe we can search for another parameters like :
`PVM_SPackArrSliceDistance`

**Comment by aTrotier** [comment]
Should be solved by [648e41f](https://github.com/MagneticResonanceImaging/MRIReco.jl/commit/648e41f6aa1f21cc6b49f1aa124e9278b05848da)
