### ISSUE TITLE
ci.yml will need a codecov token eventually

### ISSUE THREAD

**Issue by JeffFessler** [MagneticResonanceImaging/MRIReco.jl#185]
see:
https://discourse.julialang.org/t/psa-new-version-of-codecov-action-requires-additional-setup/109857

i added an org-level token

i'm addressing this in BlochSim.jl here (along with too many other changes):
https://github.com/MagneticResonanceImaging/BlochSim.jl/pull/37
just focus on the change to ci.yml

**Comment by aTrotier** [comment]
Seems it is the case
