### ISSUE TITLE
A small misalignment with the ISMRMRD standard

### ISSUE THREAD

**Issue by atsanda** [MagneticResonanceImaging/MRIReco.jl#192]
According to the schema for the ISMRMRD header, the `echoTrainLength` is not obligatory:
```xml
  <xs:complexType name="encodingType">
    <xs:all>
      ....
      <xs:element maxOccurs="1" minOccurs="0" name="echoTrainLength" type="xs:long" />
    </xs:all>
  </xs:complexType>
```
Yet, it is expected to be present in the parsing code. Here: 
https://github.com/MagneticResonanceImaging/MRIReco.jl/blob/52c3c0373e5b470dde20c6fc6bc77e0ce5f1ef06/MRIFiles/src/ISMRMRD/Parameters.jl#L181C1-L181C55

It can cause errors when trying to read a header without this field which are not self-explanatory. I propose to either add a custom error message indicating this difference with the standard or make it optional.

**Comment by tknopp** [comment]
then it should be optional

**Comment by atsanda** [comment]
I am sorry. I've double-checked the error, it turns out that the field was empty and not missing.
```xml
<echoTrainLength/>
```
Then it is expected to have an error.

**Comment by atsanda** [comment]
not a bug
