### ISSUE TITLE
Indexing in conversion from RawAcquisitionData to AcquisitionData

### ISSUE THREAD

**Issue by alexjaffray** [MagneticResonanceImaging/MRIReco.jl#20]
Dear Tobias and Mirco,

**I have noticed some unexpected behaviour when converting RawAcquisitionData to AcquisitionData in MRIReco.jl.**

My routine is as follows:
* ISMRMRD datafile -> RawData -> AcquisitionData -> Reconstruction (multiCoil) '

The ISMRMRD file contains data from a 32 coil Cartesian gradient echo scan (converted to ISMRMRD by siemens_to_ismrmrd) acquired independently at two different echo times. The two sets of data are treated as independent contrasts for my purposes. This case should be handled by a simple multiCoil reconstruction, with each contrast reconstructed independently.  

The datafile is loaded into a rawAcquisitionData object properly, and I have verified that the acquired Profiles in the RawAcquisitionData object match both the content and ordering of those in the original ISMRMRD file. 

However, after conversion to AcquisitionData, the kdata for both echoes (contrasts) is identical (this should not be the case) and is equal to the data from the first 64 (the number of excitations per contrast) profiles in the list of profiles in the RawAcquisitionData object. 

This is also strange, since the ordering of the profiles in the RawAcquisitionData object is ordered by echo/contrast
(i.e. [echo1_excitation1; echo2_excitation1; echo1_excitation2; echo2_excitation2; ... ]) rather than by excitation.

**I have seemingly fixed the issue by changing line 215 in RawAcqData.jl from:**

`for l in idx_unique`

**to:**

`for l in idx[idx_unique]`

It seems like `idx_unique` appears to only contain the indices of the unique elements of `idx`, and so if each element of `idx` is already unique, then `idx_unique` will simply be always equal to `1:length(idx)`

**After implementing this fix, the reconstruction works and produces two distinct, clear and very acceptable images, one for each echo, as expected. However, I am not sure yet (and not familiar with the code enough to know) whether this fix is generally applicable.** 

Could you possibly look into this? I can send a MWE if required. 

Thanks,
Alexander

**Comment by tknopp** [comment]
Thanks a lot, we will have a look. Ping @migrosser

**Comment by migrosser** [comment]
Thanks for pointing this out to us. I had a look at the code and the fix looks good to me. I comited it to the master for now. For the future, I think it would be a good idea to create a test that captures this kind of bug.

**Comment by tknopp** [comment]
perfect, thanks! I initiated a bug-fix release (0.3.3) and close this now.
