### ISSUE TITLE
ISMRMRD Saving and Loading

### ISSUE THREAD

**Issue by alexjaffray** [MagneticResonanceImaging/MRIReco.jl#25]
Hi Mirco and Tobias,

We are in the process of modularizing our reconstruction pipeline (which is built on MRIReco.jl) and are attempting to use the data writing functionality in MRIReco.jl to save a RawAcquisitionData object to an ISMRMRD file so that we can separate our pre-processing and reconstruction tasks. This is on Julia 1.6.1 and the master version of MRIReco.jl.

I have encountered an error during the save operation. I have provided the call stack below:

```
HDF5-DIAG: Error detected in HDF5 (1.12.0) thread 0:
  #000: D:/mingwbuild/mingw-w64-hdf5/src/hdf5-1.12.0/src/H5Tcompound.c line 392 in H5Tinsert(): unable to insert member
    major: Datatype
    minor: Unable to insert object
  #001: D:/mingwbuild/mingw-w64-hdf5/src/hdf5-1.12.0/src/H5Tcompound.c line 480 in H5T__insert(): member overlaps with another member
    major: Datatype
    minor: Unable to insert object
LoadError: Error adding field user_int to compound datatype
Stacktrace:
  [1] error(::String, ::String, ::String)
    @ Base .\error.jl:42
  [2] h5t_insert
    @ C:\Users\ajaff\.julia\packages\HDF5\iH4LA\src\api.jl:1892 [inlined]
  [3] get_hdf5type_acquisitionheader()
    @ MRIReco C:\Users\ajaff\Documents\BrainTO\Code\mrirecon-julia\dev\MRIReco\src\IO\HDF5Types.jl:126
  [4] get_hdf5type_acquisition()
    @ MRIReco C:\Users\ajaff\Documents\BrainTO\Code\mrirecon-julia\dev\MRIReco\src\IO\HDF5Types.jl:161
  [5] writeProfiles(file::HDF5.File, dataset::String, profiles::Vector{MRIReco.Profile})
    @ MRIReco C:\Users\ajaff\Documents\BrainTO\Code\mrirecon-julia\dev\MRIReco\src\IO\HDF5Types.jl:193
  [6] (::MRIReco.var"#358#359"{RawAcquisitionData, String})(file::HDF5.File)
    @ MRIReco C:\Users\ajaff\Documents\BrainTO\Code\mrirecon-julia\dev\MRIReco\src\IO\ISMRMRD.jl:82
  [7] h5open(::MRIReco.var"#358#359"{RawAcquisitionData, String}, ::String, ::Vararg{String, N} where N; swmr::Bool, pv::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ HDF5 C:\Users\ajaff\.julia\packages\HDF5\iH4LA\src\HDF5.jl:458
  [8] h5open
    @ C:\Users\ajaff\.julia\packages\HDF5\iH4LA\src\HDF5.jl:456 [inlined]
  [9] save(f::ISMRMRDFile, acq::RawAcquisitionData, dataset::String)
    @ MRIReco C:\Users\ajaff\Documents\BrainTO\Code\mrirecon-julia\dev\MRIReco\src\IO\ISMRMRD.jl:79
 [10] top-level scope
    @ C:\Users\ajaff\Documents\BrainTO\Code\mrirecon-julia\recon\julia_recon_cartesian.jl:89
 [11] eval
    @ .\boot.jl:360 [inlined]
 [12] include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String)
    @ Base .\loading.jl:1094
```

The minimum working example to reproduce this error is:

```
dataFile = ISMRMRDFile("scanFile.h5")
rawData = RawAcquisitionData(dataFile)

filename_to_save_to = "saveFile.h5"
saveFile = ISMRMRDFile(filename_to_save_to)
save(saveFile, rawData )
```
scanFile.h5 contains a standard gradient echo scan, converted from Siemens .dat format to ISMRMRD via siemens_to_ismrmrd.

I can provide scanFile.h5 to you upon request. Please let me know if you have any insight into what might be causing this error.

Cheers,
Alexander

**Comment by tknopp** [comment]
Hi Alexander, 

thanks for the bug report. No, I don't see a reason on what's going on here. We need to look into the file generated by `siemens_to_ismrmrd` to track down this bug. Could you share a private link to the data (email address, see [here](https://www.tuhh.de/ibi/people/tobias-knopp-head-of-institute.html))? I will not have a chance to look at this in the next two weeks though.

Best  Tobias

**Comment by alexjaffray** [comment]
Thanks for the quick response! I will send the datafile to you shortly. That timeline is ok with me, there is no rush as I can always write the data to a nonstandard .h5 file easily for internal use.

**Comment by tknopp** [comment]
Ok, I made some progress. The file that you send me was named "fieldMap_23_1.h5". The error I got was actually a different one than you posted here. The problem with "fieldMap_23_1.h5" was that it contained two "TE" times. I made a quick fix here https://github.com/MagneticResonanceImaging/MRIReco.jl/commit/3f2a3fadd330b9d173a107fd5dde61d0ea2c6672
that simply keeps the xml as in the original file.

Could you checkout master (] Pkg.add MRIReco#master) and test if this now works? 

But I am still confused that your original error is a different one. You error happened at writing, mine at reading.
