### ISSUE TITLE
Bruker to acquisitionData : ComplexF32 -> ComplexF64

### ISSUE THREAD

**Issue by aTrotier** [MagneticResonanceImaging/MRIReco.jl#61]
Hi,
For now data are converted to ComplexF64 at this [line](https://github.com/MagneticResonanceImaging/MRIReco.jl/blob/2978ca778d5a6c2ccef06d7988eec966ccfeb63a/src/IO/Brukerfile.jl#L311) I can use Maybe dtype = Complex{acqDataType(b)} at this step.

However during the conversion from raw to acq data are converted to ComplexF64. Is that an issue to keep the type in the acquisitionData ? I thought it was to be coherent with the MRD format but it [appears it is also de F32 ](https://github.com/MagneticResonanceImaging/MRIReco.jl/blob/2978ca778d5a6c2ccef06d7988eec966ccfeb63a/src/IO/ISMRMRD.jl#L34)

Can we keep the type all the way from conversion to reconstruction ?

**Comment by tknopp** [comment]
I am not sure anymore why I did this. But we certainly want to support `Float32`. So `dtype = Complex{acqDataType(b)}` seems like a good idea. You might find this in other places as well.

**Comment by tknopp** [comment]
Actually we have `https://github.com/MagneticResonanceImaging/MRIReco.jl/blob/2978ca778d5a6c2ccef06d7988eec966ccfeb63a/src/Datatypes/RawAcqData.jl#L55`
So the `Profile` cannot hold `ComplexF64`. Not sure where you are seeing that.

**Comment by aTrotier** [comment]
During the conversion to acq : https://github.com/MagneticResonanceImaging/MRIReco.jl/blob/2978ca778d5a6c2ccef06d7988eec966ccfeb63a/src/Datatypes/AcqData.jl#L22

**Comment by tknopp** [comment]
That is a different type, I thought the `RawDataAcquisition` type was the issue. `AcquisitionData could/should indeed be parametric in T`

**Comment by tknopp** [comment]
I think this issue is solved. If not, please reopen.
