### ISSUE TITLE
data from multiple dicom series into one

### ISSUE THREAD

**Issue by jakubMitura14** [MagneticResonanceImaging/MRIReco.jl#85]
Hello thank you for sharing your work I am wondering weather i could use your algorithms for 3d reconstruction of MRI from Dicom files

I mean for example i have three series transverse t1, saggital t1 and coronal t1 and using all of those i would like to reconstruct the single series with maximized spatial resolution, can your library can be used for it ?

Thank you !

**Comment by alexjaffray** [comment]
Hi Jakub, 

Thanks for asking about this! Unfortunately I don't think MRIReco.jl can be used for what you are trying to do, at least not directly.  

MRIReco.jl is a tool for reconstructing MR images from raw k-space data. DICOM data is usually already reconstructed, and so MRIReco.jl is of limited use to your application (which is not image reconstruction in the MRI sense, but rather superresolution).

Something like the following might be a method you'd be interested in, and some functions of MRIReco.jl might be useful for implementing parts of it:

https://www.sciencedirect.com/science/article/pii/S1110866513000194

I hope that helps!

**Comment by jakubMitura14** [comment]
Thank you !
